Fix crash due to partial initialization of StdioTransport
This should fix crashes due to these fatalError() calls:

ContextCore/StdioTransport.swift:423: Fatal error: Cannot send messages before stdin is available. Make sure to call start() first

ContextCore/StdioTransport.swift:252: Fatal error: Cannot receive messages before stdout is available. Make sure to call start() first